### ISSUE TITLE
cpod crashes every time a make a search 

### ISSUE THREAD

**Issue by Lvaskz** [snapcrafters/cumulonimbus#2] opened 2018-10-01 19:14 UTC
cpod crashes every time a make a search 
}ubuntu 18.04
64 bit 
gnome 3.28.1

**Comment by carlos-tovar** [comment] 2019-01-20 02:23
Same, ubuntu 18.04, 64 bit, gnome 3.28.2

The issue is gone on cpod 1.17.0, but I had to launch Cpod by running  /snap/cumulonimbus/58/opt/CPod/cpod   directly as I was getting a file not found error

"/snap/cumulonimbus/58/bin/desktop-launch: line 544: /snap/cumulonimbus/58/opt/CPod/cumulonimbus: No such file or directory"

**Comment by YamiYukiSenpai** [comment] 2019-05-02 23:08
I'm attaching [the output](https://github.com/snapcrafters/cumulonimbus/files/3140233/cumulonimbus_error.txt) after running `$ snap run cumulonimbus`.  Hope it helps.

**Comment by wenderRondonia** [comment] 2019-07-01 14:39
the [repository](https://github.com/z-------------/CPod) from zack guard with the new version is already fixed, install from there

**Comment by YamiYukiSenpai** [comment] 2019-07-22 05:16
Nope.  The Edge channel is already on 1.27.1.  It hasn't been updated since then.

**Comment by RickAndTired** [comment] 2019-09-14 06:14
Stable and Edge both crash when clicking on Search or when Tabbing to the Search bar.
The Appimage works fine.

[cpod-stable.txt](https://github.com/snapcrafters/cumulonimbus/files/3612378/cpod-stable.txt)
[cpod-edge.txt](https://github.com/snapcrafters/cumulonimbus/files/3612379/cpod-edge.txt)

**Comment by merlijn-sebrechts** [comment] 2022-11-09 17:03
This is fixed in the latest version in edge and will soon be published to stable. Thanks for reporting this!

**Closed as completed by merlijn-sebrechts** 2022-11-09 17:03 UTC
